// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#ifndef PROTOBUF_config_2eproto__INCLUDED
#define PROTOBUF_config_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace shm_serving {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_config_2eproto();
void protobuf_AssignDesc_config_2eproto();
void protobuf_ShutdownFile_config_2eproto();

class NamedLoader;
class DataServiceConfig;

// ===================================================================

class NamedLoader : public ::google::protobuf::Message {
 public:
  NamedLoader();
  virtual ~NamedLoader();
  
  NamedLoader(const NamedLoader& from);
  
  inline NamedLoader& operator=(const NamedLoader& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const NamedLoader& default_instance();
  
  void Swap(NamedLoader* other);
  
  // implements Message ----------------------------------------------
  
  NamedLoader* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NamedLoader& from);
  void MergeFrom(const NamedLoader& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string file_name = 1;
  inline bool has_file_name() const;
  inline void clear_file_name();
  static const int kFileNameFieldNumber = 1;
  inline const ::std::string& file_name() const;
  inline void set_file_name(const ::std::string& value);
  inline void set_file_name(const char* value);
  inline void set_file_name(const char* value, size_t size);
  inline ::std::string* mutable_file_name();
  inline ::std::string* release_file_name();
  
  // optional bool exclusive = 2;
  inline bool has_exclusive() const;
  inline void clear_exclusive();
  static const int kExclusiveFieldNumber = 2;
  inline bool exclusive() const;
  inline void set_exclusive(bool value);
  
  // @@protoc_insertion_point(class_scope:shm_serving.NamedLoader)
 private:
  inline void set_has_file_name();
  inline void clear_has_file_name();
  inline void set_has_exclusive();
  inline void clear_has_exclusive();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* file_name_;
  bool exclusive_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_config_2eproto();
  friend void protobuf_AssignDesc_config_2eproto();
  friend void protobuf_ShutdownFile_config_2eproto();
  
  void InitAsDefaultInstance();
  static NamedLoader* default_instance_;
};
// -------------------------------------------------------------------

class DataServiceConfig : public ::google::protobuf::Message {
 public:
  DataServiceConfig();
  virtual ~DataServiceConfig();
  
  DataServiceConfig(const DataServiceConfig& from);
  
  inline DataServiceConfig& operator=(const DataServiceConfig& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DataServiceConfig& default_instance();
  
  void Swap(DataServiceConfig* other);
  
  // implements Message ----------------------------------------------
  
  DataServiceConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DataServiceConfig& from);
  void MergeFrom(const DataServiceConfig& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .shm_serving.NamedLoader named_loaders = 1;
  inline int named_loaders_size() const;
  inline void clear_named_loaders();
  static const int kNamedLoadersFieldNumber = 1;
  inline const ::shm_serving::NamedLoader& named_loaders(int index) const;
  inline ::shm_serving::NamedLoader* mutable_named_loaders(int index);
  inline ::shm_serving::NamedLoader* add_named_loaders();
  inline const ::google::protobuf::RepeatedPtrField< ::shm_serving::NamedLoader >&
      named_loaders() const;
  inline ::google::protobuf::RepeatedPtrField< ::shm_serving::NamedLoader >*
      mutable_named_loaders();
  
  // @@protoc_insertion_point(class_scope:shm_serving.DataServiceConfig)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::shm_serving::NamedLoader > named_loaders_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_config_2eproto();
  friend void protobuf_AssignDesc_config_2eproto();
  friend void protobuf_ShutdownFile_config_2eproto();
  
  void InitAsDefaultInstance();
  static DataServiceConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// NamedLoader

// required string file_name = 1;
inline bool NamedLoader::has_file_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NamedLoader::set_has_file_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NamedLoader::clear_has_file_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NamedLoader::clear_file_name() {
  if (file_name_ != &::google::protobuf::internal::kEmptyString) {
    file_name_->clear();
  }
  clear_has_file_name();
}
inline const ::std::string& NamedLoader::file_name() const {
  return *file_name_;
}
inline void NamedLoader::set_file_name(const ::std::string& value) {
  set_has_file_name();
  if (file_name_ == &::google::protobuf::internal::kEmptyString) {
    file_name_ = new ::std::string;
  }
  file_name_->assign(value);
}
inline void NamedLoader::set_file_name(const char* value) {
  set_has_file_name();
  if (file_name_ == &::google::protobuf::internal::kEmptyString) {
    file_name_ = new ::std::string;
  }
  file_name_->assign(value);
}
inline void NamedLoader::set_file_name(const char* value, size_t size) {
  set_has_file_name();
  if (file_name_ == &::google::protobuf::internal::kEmptyString) {
    file_name_ = new ::std::string;
  }
  file_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* NamedLoader::mutable_file_name() {
  set_has_file_name();
  if (file_name_ == &::google::protobuf::internal::kEmptyString) {
    file_name_ = new ::std::string;
  }
  return file_name_;
}
inline ::std::string* NamedLoader::release_file_name() {
  clear_has_file_name();
  if (file_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = file_name_;
    file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional bool exclusive = 2;
inline bool NamedLoader::has_exclusive() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NamedLoader::set_has_exclusive() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NamedLoader::clear_has_exclusive() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NamedLoader::clear_exclusive() {
  exclusive_ = false;
  clear_has_exclusive();
}
inline bool NamedLoader::exclusive() const {
  return exclusive_;
}
inline void NamedLoader::set_exclusive(bool value) {
  set_has_exclusive();
  exclusive_ = value;
}

// -------------------------------------------------------------------

// DataServiceConfig

// repeated .shm_serving.NamedLoader named_loaders = 1;
inline int DataServiceConfig::named_loaders_size() const {
  return named_loaders_.size();
}
inline void DataServiceConfig::clear_named_loaders() {
  named_loaders_.Clear();
}
inline const ::shm_serving::NamedLoader& DataServiceConfig::named_loaders(int index) const {
  return named_loaders_.Get(index);
}
inline ::shm_serving::NamedLoader* DataServiceConfig::mutable_named_loaders(int index) {
  return named_loaders_.Mutable(index);
}
inline ::shm_serving::NamedLoader* DataServiceConfig::add_named_loaders() {
  return named_loaders_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::shm_serving::NamedLoader >&
DataServiceConfig::named_loaders() const {
  return named_loaders_;
}
inline ::google::protobuf::RepeatedPtrField< ::shm_serving::NamedLoader >*
DataServiceConfig::mutable_named_loaders() {
  return &named_loaders_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace shm_serving

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_config_2eproto__INCLUDED
